additions for top related analyses
KIT-CMS/CROWN pull request #200
Opened 2023-02-15 09:56 UTC by nfaltermann

2023-02-15 13:07 UTC, harrypuuter requested changes
a few smaller remarks. see above :+1:

2023-02-15 13:07 UTC, harrypuuter commented on code_generation/subset_template.cxx
> +ROOT::RDF::RNode{subsetname}(ROOT::RDF::RNode df0) {
spaces are needed here: 

```
ROOT::RDF::RNode {subsetname} (ROOT::RDF::RNode df0) {
```

2023-02-16 10:05 UTC, nfaltermann commented on src/jets.cxx
> +                             const int index = jetcollection.at(position);
thanks for the suggestion, changed accordingly

2023-02-16 10:06 UTC, nfaltermann commented on src/topreco.cxx
> +
added

2023-02-16 10:07 UTC, nfaltermann commented on code_generation/subset_template.cxx
> +ROOT::RDF::RNode{subsetname}(ROOT::RDF::RNode df0) {
clang -.-

2023-02-16 13:52 UTC, harrypuuter approved these changes
thats a 👍 from me

2023-02-16 13:53 UTC, harrypuuter commented
there are still two python files where black is complaining, the error in the build test is unrelated, so I guess we just ignore it :D

2023-02-17 08:50 UTC, merged