implementation of WH(tautau) analysis
KIT-CMS/CROWN pull request #216
Opened 2023-04-25 09:19 UTC by ralfschmieder

2023-04-27 12:19 UTC, harrypuuter requested changes
Some smaller remarks; the rest looks fine ! (although I did not check the triple selection code, since you are the only user of it ;) )

2023-04-27 12:19 UTC, harrypuuter commented on src/lorentzvectors.cxx
> +            auto dileptonsystem_scaled = 0.47*dileptonsystem;
why not use a more generic implementation, where you can configure this correction factor ? From what I see, the lt and tt functions are identical apart from the 0.47 and the 0.69

2023-04-27 12:19 UTC, harrypuuter commented on src/quantities.cxx
> +ROOT::RDF::RNode Lt(ROOT::RDF::RNode df, const std::string &outputname,
choose a more descriptive name like sum_pts()

2023-04-27 12:19 UTC, harrypuuter commented on src/quantities.cxx
> +ROOT::RDF::RNode phi_vis(ROOT::RDF::RNode df, const std::string &outputname,
same as above

2023-04-28 06:53 UTC, ralfschmieder commented on src/quantities.cxx
> +ROOT::RDF::RNode eta_vis(ROOT::RDF::RNode df, const std::string &outputname,
I think it is more consistent to use eta_vis and phi_vis, since we have also m_vis and pt_vis

2023-04-28 14:19 UTC, harrypuuter requested changes

2023-04-28 14:19 UTC, harrypuuter commented on src/lorentzvectors.cxx
> +        [p4_miss_sf](const ROOT::Math::PtEtaPhiMVector &p4_23) {
use general names here: scale and p4 should be fine

2023-04-28 14:30 UTC, harrypuuter approved these changes
👍🏼

2023-04-28 14:55 UTC, merged