implementation of fake factors for full hadronic channel
KIT-CMS/CROWN pull request #224
Opened 2023-06-21 12:36 UTC by nshadskiy

2023-06-22 09:34 UTC, harrypuuter requested changes
looks fine by me, one small remark, going forward I would like to switch to the @param instead of \param for the documentation, since this is handled a bit better by doxygen and clang-format

2023-06-22 09:38 UTC, harrypuuter commented
do you already use the changes in #210 concerning the performance of the semileptonic channels ?

2023-06-22 11:04 UTC, nshadskiy commented
I changed it now to @param. And yes, https://github.com/KIT-CMS/CROWN/pull/210 is actually already included.

2023-06-30 13:29 UTC, harrypuuter approved these changes

2023-06-30 13:29 UTC, merged