Additional functions for hadronic recoil quantities
KIT-CMS/CROWN pull request #273
Opened 2024-07-17 14:45 UTC by moritzmolch

This pull request introduces functions to calculate quantities, which are related to the hadronic recoil in an event.

- `hadrecoil::scalar_ht` takes a jet pt column and a column with indices of selected jets as input. The output is the scalar sum of the magnitude of the transverse momentum of the selected jets.

- `hadrecoil::vectorial_mht` takes a jet pt column, a jet phi column and a column with indices of selected jets as input. The output is the negative vectorial sum of the transverse momentum vectors of the selected jets.

TODOs:
- [ ] add documentation strings to the new functions
- [ ] Add producers to the python configuration

2024-07-17 14:56 UTC, moritzmolch commented
Producers have been added to the config via this pull request: https://github.com/KIT-CMS/TauAnalysis-CROWN/pull/50.

2024-07-22 11:25 UTC, harrypuuter requested changes

2024-07-22 11:25 UTC, harrypuuter commented on src/hadrecoil.cxx
> +            auto jet_pt_vec = dynamic_cast<ROOT::Math::PtEtaPhiMVector>(ROOT::Math::PtEtaPhiEVector(jet_pt.at(jet_index), jet_eta.at(jet_index), 0., jet_pt.at(jet_index)));
Why not use pt, eta, phi and Mass of the jets, this information is available in NanoAOD

2024-07-22 11:25 UTC, harrypuuter commented on src/hadrecoil.cxx
> +            ht += jet_pt.at(jet_index);
I would like to see thisa implemented as a a basefunction in a more generic way

2024-07-22 11:25 UTC, harrypuuter commented on src/hadrecoil.cxx
> +            mht -= jet_pt_vec;
same as above, implement as a basefunction (maybe the negative sum as well as the positive)

2024-07-24 13:25 UTC, harrypuuter reviewed
one remark to use RVec::Construct rest looks good!

2024-07-24 13:25 UTC, harrypuuter commented on include/basefunctions.hxx
> +
There is https://root.cern/doc/master/group__vecops.html#ga84ffef84f7829e9d904cd92a57a0cd9a to further shorten this code and eliminate the for-loop

2024-07-24 13:43 UTC, moritzmolch commented
@harrypuuter I added your suggestions, the compiled binary runs on a DY sample without errors. I still have to check if the functions' outputs are reasonable.

2024-07-24 13:46 UTC, harrypuuter approved these changes
looks good, I approve and you just merge it ones the results are validated

2024-07-24 13:51 UTC, nshadskiy commented
Thanks for all the checks Sebastian! As it is now this PR would only be merged to my nmssm_devs branch. I guess we could merge it directly into the main branch, since nothing directly related to the NMSSM analysis is involved in the code changes.

2024-07-24 14:07 UTC, harrypuuter commented
yes, i would merge this directly to main as well

2025-02-27 09:26 UTC, nshadskiy commented
This PR will be closed because the implementation is now directly merged to main by https://github.com/KIT-CMS/CROWN/pull/300

2025-02-27 09:26 UTC, closed without merging