WIP: add generic workspace producer
KIT-CMS/CROWN pull request #50
Opened 2021-05-31 13:41 UTC by harrypuuter

Documentation still pending

2021-06-01 09:32 UTC, harrypuuter commented
This closes #38

2021-06-01 10:37 UTC, swozniewski requested changes
Great! I only spotted some minor issues.

2021-06-01 10:37 UTC, swozniewski commented on code_generation/producers/scalefactors.py
> +MuonIso_SF = Producer(
This should be MuonID_SF?

2021-06-01 10:37 UTC, swozniewski commented on code_generation/producers/scalefactors.py
> +MuonID_SF = Producer(
and this MuonIso_SF?

2021-06-01 10:37 UTC, swozniewski commented on code_generation/producers/scalefactors.py
> +MuonID_SF = Producer(
or MuonIDIso_SF. I think it would be good to have the same for attribute 'name'

2021-06-01 10:37 UTC, swozniewski commented on scalefactors.hxx
> +    // workspace->argSet(id_arguments.c_str()).Print();
I'd suggest to either delete these rows or turn them into log debug

2021-06-07 08:56 UTC, swozniewski requested changes

2021-06-07 12:53 UTC, harrypuuter commented on basefunctions.hxx
> +        }
true, changed !

2021-06-07 14:14 UTC, merged